puts "The students of Villains Academy"
puts "--------------"
puts "Dr . Hannibal Lecter"
puts "Nurse Ratched"
puts "Michael Corleone"
puts "Alex DeLarge"
puts "The wicked Witch of the west"
puts "Terminator"
puts "Freddy Krueger"
puts "The Joker"
puts "Joffrey Baratheon"
puts "Norman Bates"

